name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version and create tag
        id: version
        run: |
            VERSION=$(date +'%Y.%m.%d.%H%M')
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install --workspace=backend
          npm install --workspace=frontend
          npm install
          npm run build

      - name: Create release package
        run: |
          mkdir -p jslib-${{ github.ref_name }}
          cp -r backend/dist jslib-${{ github.ref_name }}/
          cp -r backend/node_modules jslib-${{ github.ref_name }}/
          cp backend/package.json jslib-${{ github.ref_name }}/
          tar -czf jslib-${{ github.ref_name }}.tar.gz jslib-${{ github.ref_name }}/

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
              jslib-${{ github.ref_name }}.tar.gz
          draft: false
