name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install --workspace=backend
        npm install --workspace=frontend
        npm install
        npm run build
        
    - name: Create release package
      run: |
        mkdir -p jslib-${{ github.ref_name }}
        cp -r backend/dist jslib-${{ github.ref_name }}/
        tar -czf jslib-${{ github.ref_name }}.tar.gz jslib-${{ github.ref_name }}/

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
            jslib-${{ github.ref_name }}.tar.gz
        draft: false
